# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install uv, which is a tool to handle virtual environments efficiently
RUN pip install uv

# Install the required packages for the project
RUN uv tool install llm-context

# Set the command to run the MCP server
CMD ["uvx", "--from", "llm-context", "lc-mcp"]